pipeline:

  publish:
    cache_from:
      - "ethicaljobs/yode:latest"
    image: plugins/docker
    repo: ethicaljobs/yode
    secrets: [ docker_username, docker_password ]
    build_args: [ 'VERSION_TAG=${DRONE_TAG=latest}' ]
    tags: [ 'latest', '${DRONE_TAG=${DRONE_COMMIT}}' ]      
    when:
      event: tag

  notify-slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: deployments
    failure: ignore
    when:
      event: tag

