pipeline:

  publish:
    image: plugins/docker
    repo: ethicaljobs/yode
    username: ${DOCKER_USERNAME}
    password: ${DOCKER_PASSWORD}
    tags:
      - latest
      - ${DRONE_TAG}
    when:
      event: tag      

  notify-slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: deployments
    when:
      status: changed
